services:
  ipa:
    hostname: ipa.example.test
    container_name: ipa
    image: freeipa/freeipa-server:fedora-39-4.11.1
    #cgroup: private
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      #- DEBUG_TRACE=1
      - IPA_SERVER_INSTALL_OPTS=-r EXAMPLE.TEST -N -U --skip-mem-check
      - PASSWORD=password
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
